export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS';

export const FETCH_USER = 'FETCH_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ADD_USER_EVENT = 'ADD_USER_EVENT';
export const CHANGE_USER_CONTACT = 'CHANGE_USER_CONTACT';
